### ISSUE TITLE
Kubernettes dev env setup

### ISSUE THREAD

**Issue by kjgarza** [datacite/mastino#1]
We need the ability to ensure we can easily create a consistent development environment.

Notes from Dec 8th Meeting:
* Achieve a similar setup in your local environment to production to ensure consistency.
* This will include having all of the same stack like MySQL, Redis, etc
* Help to manage environment variables for each container. Possibility: Helm
* How do we handle Hosted services like AWS Elasticsearch?

**Comment by mfenner** [comment]
Will revisit when we start using Kubernetes in production.
