### ISSUE TITLE
redirect for schema site

### ISSUE THREAD

**Issue by daslerr** [datacite/mastino#73]
I set up json routing rules for the schema site (see /services/schema), but the rule to reroute https://search.datacite.org/dc2ap results in a 404. I'm not sure what I did incorrectly. 

https://github.com/datacite/mastino/commit/32876ce92e9254b2455f7a42069469451bcaf817

**Comment by kjgarza** [comment]
fixed https://github.com/datacite/mastino/commit/244337633d2218ee660e996aa1bae27385bcdf95
